BEGIN TRANSACTION;

-- Users
CREATE TRIGGER IF NOT EXISTS users_update_trigger
AFTER UPDATE ON Users
FOR EACH ROW
BEGIN
    UPDATE Users SET Updated = CURRENT_TIMESTAMP WHERE ID = NEW.ID;
END;

-- Channels
CREATE TRIGGER IF NOT EXISTS channels_update_trigger
AFTER UPDATE ON Channels
FOR EACH ROW
BEGIN
    UPDATE Channels SET Updated = CURRENT_TIMESTAMP WHERE ID = NEW.ID;
END;

-- Posts
CREATE TRIGGER IF NOT EXISTS posts_update_trigger
AFTER UPDATE ON Posts
FOR EACH ROW
BEGIN
    UPDATE Posts SET Updated = CURRENT_TIMESTAMP WHERE ID = NEW.ID;
END;

-- Comments
CREATE TRIGGER IF NOT EXISTS comments_update_trigger
AFTER UPDATE ON Comments
FOR EACH ROW
BEGIN
    UPDATE Comments SET Updated = CURRENT_TIMESTAMP WHERE ID = NEW.ID;
END;

-- Bookmarks
CREATE TRIGGER IF NOT EXISTS bookmarks_update_trigger
AFTER UPDATE ON Bookmarks
FOR EACH ROW
BEGIN
    UPDATE Bookmarks SET Updated = CURRENT_TIMESTAMP WHERE ID = NEW.ID;
END;

-- Flags
CREATE TRIGGER IF NOT EXISTS flags_update_trigger
AFTER UPDATE ON Flags
FOR EACH ROW
BEGIN
    UPDATE Flags SET Updated = CURRENT_TIMESTAMP WHERE ID = NEW.ID;
END;

-- Followers
CREATE TRIGGER IF NOT EXISTS followers_update_trigger
AFTER UPDATE ON Followers
FOR EACH ROW
BEGIN
    UPDATE Followers SET Updated = CURRENT_TIMESTAMP WHERE ID = NEW.ID;
END;

-- Following
CREATE TRIGGER IF NOT EXISTS following_update_trigger
AFTER UPDATE ON Following
FOR EACH ROW
BEGIN
    UPDATE Following SET Updated = CURRENT_TIMESTAMP WHERE ID = NEW.ID;
END;

-- Images
CREATE TRIGGER IF NOT EXISTS images_update_trigger
AFTER UPDATE ON Images
FOR EACH ROW
BEGIN
    UPDATE Images SET Updated = CURRENT_TIMESTAMP WHERE ID = NEW.ID;
END;

-- Memberships
CREATE TRIGGER IF NOT EXISTS memberships_update_trigger
AFTER UPDATE ON Memberships
FOR EACH ROW
BEGIN
    UPDATE Memberships SET Updated = CURRENT_TIMESTAMP WHERE ID = NEW.ID;
END;

-- Mods
CREATE TRIGGER IF NOT EXISTS mods_update_trigger
AFTER UPDATE ON Mods
FOR EACH ROW
BEGIN
    UPDATE Mods SET Updated = CURRENT_TIMESTAMP WHERE ID = NEW.ID;
END;

-- MutedChannels
CREATE TRIGGER IF NOT EXISTS mutedchannels_update_trigger
AFTER UPDATE ON MutedChannels
FOR EACH ROW
BEGIN
    UPDATE MutedChannels SET Updated = CURRENT_TIMESTAMP WHERE ID = NEW.ID;
END;

-- Notifications
CREATE TRIGGER IF NOT EXISTS notifications_update_trigger
AFTER UPDATE ON Notifications
FOR EACH ROW
BEGIN
    UPDATE Notifications SET Updated = CURRENT_TIMESTAMP WHERE ID = NEW.ID;
END;

-- NotificationsUsers
CREATE TRIGGER IF NOT EXISTS notificationsusers_update_trigger
AFTER UPDATE ON NotificationsUsers
FOR EACH ROW
BEGIN
    UPDATE NotificationsUsers SET Updated = CURRENT_TIMESTAMP WHERE ID = NEW.ID;
END;

-- PostChannels
CREATE TRIGGER IF NOT EXISTS postchannels_update_trigger
AFTER UPDATE ON PostChannels
FOR EACH ROW
BEGIN
    UPDATE PostChannels SET Updated = CURRENT_TIMESTAMP WHERE ID = NEW.ID;
END;

-- PostImages
CREATE TRIGGER IF NOT EXISTS postimages_update_trigger
AFTER UPDATE ON PostImages
FOR EACH ROW
BEGIN
    UPDATE PostImages SET Updated = CURRENT_TIMESTAMP WHERE ID = NEW.ID;
END;

-- PostReplies
CREATE TRIGGER IF NOT EXISTS postreplies_update_trigger
AFTER UPDATE ON PostReplies
FOR EACH ROW
BEGIN
    UPDATE PostReplies SET Updated = CURRENT_TIMESTAMP WHERE ID = NEW.ID;
END;

-- Reactions
CREATE TRIGGER IF NOT EXISTS reactions_update_trigger
AFTER UPDATE ON Reactions
FOR EACH ROW
BEGIN
    UPDATE Reactions SET Updated = CURRENT_TIMESTAMP WHERE ID = NEW.ID;
END;

-- Rules
CREATE TRIGGER IF NOT EXISTS rules_update_trigger
AFTER UPDATE ON Rules
FOR EACH ROW
BEGIN
    UPDATE Rules SET Updated = CURRENT_TIMESTAMP WHERE ID = NEW.ID;
END;

-- ChannelsRules
CREATE TRIGGER IF NOT EXISTS channelsrules_update_trigger
AFTER UPDATE ON ChannelsRules
FOR EACH ROW
BEGIN
    UPDATE ChannelsRules SET Updated = CURRENT_TIMESTAMP WHERE ID = NEW.ID;
END;

-- Chats: Update LastActive when a new message is inserted
CREATE TRIGGER IF NOT EXISTS chats_lastactive_trigger
AFTER INSERT ON Messages
FOR EACH ROW
BEGIN
    UPDATE Chats SET LastActive = CURRENT_TIMESTAMP WHERE ID = NEW.ChatID;
END;

COMMIT;

