INSERT INTO PostChannels (PostID, ChannelID, Created)
VALUES 
  (1,  4, CURRENT_TIMESTAMP),
  (2,  7, CURRENT_TIMESTAMP),
  (3,  9, CURRENT_TIMESTAMP),
  (4,  1, CURRENT_TIMESTAMP),
  (5,  6, CURRENT_TIMESTAMP),
  (6,  8, CURRENT_TIMESTAMP),
  (7,  4, CURRENT_TIMESTAMP),
  (8,  9, CURRENT_TIMESTAMP),
  (9,  7, CURRENT_TIMESTAMP),
  (10, 1, CURRENT_TIMESTAMP),
  (11, 6, CURRENT_TIMESTAMP),
  (12, 8, CURRENT_TIMESTAMP),
  (13, 4, CURRENT_TIMESTAMP),
  (14, 7, CURRENT_TIMESTAMP),
  (15, 9, CURRENT_TIMESTAMP),
  (16, 1, CURRENT_TIMESTAMP),
  (17, 6, CURRENT_TIMESTAMP),
  (18, 8, CURRENT_TIMESTAMP),
  (19, 4, CURRENT_TIMESTAMP),
  (20, 7, CURRENT_TIMESTAMP);

